{% set name = "check-jsonschema" %}
{% set version = "0.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/check_jsonschema-{{ version }}.tar.gz
  sha256: e1078b6e42c5e05c1a807252ac5b26b8fa2c826bad57fe9f5dd15ea27d40e16e

build:
  noarch: python
  entry_points:
    - check-jsonschema = check_jsonschema:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - tomli >=2.0
    - ruamel.yaml >=0.18.10,<0.19.0
    - jsonschema >=4.18.0,<5.0
    - regress >=2024.11.1
    - requests <3.0
    - click >=8,<9

test:
  commands:
    - pip check
    - check-jsonschema --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/python-jsonschema/check-jsonschema
  summary: A jsonschema CLI and pre-commit hook
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - freundTech
