schema_version: 1

context:
  name: check-jsonschema
  version: "0.38.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/check_jsonschema-${{ version }}.tar.gz
  sha256: 6b358ad8da9a41d7a61707739aa016564f4745bcb28899bd3b62739092e96bac

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - check-jsonschema = check_jsonschema:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.2
    - pip
  run:
    - python >=${{ python_min }}
    - tomli >=2.0
    - ruamel.yaml >=0.18.10,<0.20.0
    - jsonschema >=4.18.0,<5.0
    - regress >=2024.11.1
    - requests <3.0
    - click >=8.5,<9  # Upstream declared wrong minimum version. We fixed it. Fixed upstream in 0.38.2

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check
      - check-jsonschema --help

about:
  summary: A jsonschema CLI and pre-commit hook
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python-jsonschema/check-jsonschema

extra:
  recipe-maintainers:
    - freundTech
